name: Deploy Lambda Function

on:
  push:
    paths:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install zip tool
        uses: montudor/action-zip@v1v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run:
          python -m pip install -- upgrade pip
          pip install -r requirements.txt
      - name: Set up Python
        uses: actions/set-python@v2
      - name: Create zip file for lambda
        run: cd src && zip -r code.zip .
      - name: AWS CLI v2
        uses: imehedi/actions-awscli-v2@latest
        with:
          args: "lambda update-function-code \
           --arn:aws:lambda:us-east-1:733529898541:function:download_source_data \
           --zip-file fileb://code.zip"
        env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         AWS_DEFAULT_REGION: "us-east-1" 